name: Deploy FastAPI to Amazon Lightsail

on:
  push:
    branches: [ "main" ]

env:
  LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install SSH and sshpass
      run: sudo apt-get install -y openssh-client sshpass

    - name: Deploy to Amazon Lightsail using sshpass
      env:
        MINIO_IMAGE: ${{ steps.build-minio-image.outputs.minio_image }}
      run: |
        echo "Deploying image: $MINIO_IMAGE"
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -tt -o StrictHostKeyChecking=no $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP << EOF
          
          # Stop and remove existing containers
          sudo docker stop minio_container || true
          sudo docker rm minio_container || true
          
          # Run new container with MinIO console enabled
          docker run -d --name minio -v /oms/minio:/data \
          --network host \
          -e "MINIO_ROOT_USER=minio" \
          -e "MINIO_ROOT_PASSWORD=minio1234" \
          minio/minio server /data
        EOF
